"use client";
import DataList from "./components/DataList";
import InputForm from "./components/InputForm";
import NoDataBox from "./components/NoDataBox";
import ResetButton from "./components/ResetButton";
import ResultCard from "./components/ResultCard";
import React, { useCallback, useEffect, useState } from "react";
import { Metadata } from "next";

// export const metadata = {
//   title: "cco",
//   description: "Generated by Next.js",
// };

// export const generateMetadata = ({param}):Metadata => {
//   return {
//     title: 'cco'
//   }
// }

const ComparisonPage = () => {
  const [items, setItems] = useState<any>(
    (typeof window !== "undefined" &&
      JSON.parse(localStorage.getItem("items")!)) ||
      [],
  );

  const wrapperSetItem = useCallback(
    (value: any) => {
      setItems(value);
    },
    [setItems],
  );

  const handleForm = (value: any) => {
    setItems((prev: any) => [...prev, value]);
  };

  const handleRemove = (e: any) => {
    setItems((prev: any) => prev.filter((data: any) => data.id !== e.id));
  };

  useEffect(() => {
    const data = localStorage.getItem("items");
    if (data !== null) {
      setItems(JSON.parse(data));
    }
  }, []);

  useEffect(() => {
    localStorage.setItem("items", JSON.stringify(items));
  }, [items]);

  return (
    <section>
      <article className="fixed w-full top-0 bg-base-content h-[72px]">
        <div className="flex justify-end p-3">
          <ResetButton wrapper={wrapperSetItem} />
        </div>

        {/* <div className="absolute top-10 left-1/2 -translate-x-1/2">
          <ResultCard items={items} />
        </div> */}
        <div className="absolute top-10 left-1/2 -translate-x-1/2">
          <ResultCard items={items} />
        </div>
      </article>

      <article className="mt-[120px] mb-3 min-h-[calc(100svh-231px)] max-w-screen-sm mx-auto">
        <div id="container" className="overflow-y-scrollx">
          {items.length !== 0 ? (
            <DataList items={items} removeId={handleRemove} />
          ) : (
            <NoDataBox />
          )}
        </div>
      </article>

      <div className="w-full h-[100px] bg-base-content p-2">
        <InputForm formData={handleForm} />
      </div>
    </section>
  );
};

export default ComparisonPage;
