import Navbar from "@/components/Navbar";
import "@/styles/globals.css";

export const metadata = {
  title: "nadesh52",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Navbar />
        <div className="flex flex-col bg-slate-100">
          <main className="min-h-[calc(100svh-75px)] w-full">{children}</main>
          <footer className="p-1 text-center">
            <p className="text-sm">nadesh52</p>
          </footer>
        </div>
      </body>
    </html>
  );
}
