import "@/styles/globals.css";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <div className="bg-slate-100 flex flex-col">
          <main className="min-h-[calc(100svh-75px)]">{children}</main>
          <footer className="p-1 text-center">
            <p className="text-sm">nadesh52</p>
          </footer>
        </div>
      </body>
    </html>
  );
}
