import React from "react";
import FixedPlan from "./components/FixedPlan";
import ResultBox from "./components/ResultBox";
import SavingPlan from "./components/SavingPlan";
import { ResultProvider } from "./contexts/ResultContext";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Interest Calculator",
  description: "Generated by Next.js",
};

const InterestCalcPage = () => {
  return (
    <ResultProvider>
      <section className="mx-auto md:my-20 flex flex-col md:flex-row max-w-screen-md items-start gap-4 p-4">
        <div role="tablist" className="tabs tabs-lifted w-full">
          <input
            type="radio"
            name="tabs"
            role="tab"
            className="tab text-md italic [--tab-border-color:black]"
            aria-label="Saving Plan"
            defaultChecked
          />
          <div
            role="tabpanel"
            className="tab-content border-primary bg-base-100 p-6 pt-10"
          >
            <SavingPlan />
          </div>

          <input
            type="radio"
            name="tabs"
            role="tab"
            className="tab text-md italic [--tab-border-color:black]"
            aria-label="Fixed Plan"
          />
          <div
            role="tabpanel"
            className="tab-content border-primary bg-base-100 p-6 pt-10"
          >
            <FixedPlan />
          </div>
        </div>

        <ResultBox />
      </section>
    </ResultProvider>
  );
};

export default InterestCalcPage;
