import Navbar from "@/components/Navbar";
import "@/styles/globals.css";

export const metadata = {
  title: "nadesh52",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <div className="mx-auto flex max-w-screen-sm flex-col shadow-lg">
          <Navbar />
          <main className="relative min-h-[calc(100svh-52px)]">{children}</main>
          <footer className="p-1 text-center">
            <p className="text-sm">nadesh52</p>
          </footer>
        </div>
      </body>
    </html>
  );
}
