import "@/styles/globals.css";

export const metadata = {
  title: "nadesh52",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="bg-base">
        <main>{children}</main>
        <footer className="absolute bottom-0 left-1/2 -translate-x-1/2 p-2">
          <span className="text-sm">nadesh52</span>
        </footer>
      </body>
    </html>
  );
}
