import Navbar from "@/components/Navbar";
import "@/styles/globals.css";

export const metadata = {
  title: "nadesh52",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="bg-base">
        <div className="flex flex-col">
          <Navbar />
          <main className="min-h-[calc(100svh-75px)] p-8">{children}</main>
          <footer className="h- bg-purple-600 p-1 text-center">
            <p className="text-sm">nadesh52</p>
          </footer>
        </div>
      </body>
    </html>
  );
}
