import "@/styles/globals.css";

export const metadata = {
  title: "Pokedex",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <main className="min-h-[calc(100svh-23px)]">{children}</main>
      </body>
    </html>
  );
}
