import '@/styles/globals.css'

export const metadata = {
  title: {
    default: "nadesh52",
    template: "%s | nadesh52"
  },
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <main className='bg-slate-100'>{children}</main>
      </body>
    </html>
  );
}